# Introduction to Numpy

In [14]:
import numpy as np

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Numpy is fast

In [2]:
# without numpy
from time import time

a = list(range(100000))
sum = 0 

begin_time = time()
for i in range(100000):
    sum += a[i] ** 2

end_time = time()
t1 = end_time - begin_time
print(t1)

0.2955131530761719


In [3]:
# with numpy

a = np.arange(100000)

begin_time = time()
sum = np.dot(a, a)
end_time = time()

t2 = end_time - begin_time
print(t2)

0.0010256767272949219


In [11]:
print(a.ndim)

1


In [13]:
print(a.shape)

(100000,)


In [4]:
print("ratio", t1/t2)

ratio 288.11529521152954


## Broadcasting

In [5]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i] = x[i] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
