# PyTorch

In [33]:
import torch

### Tensor

In [31]:
t = torch.ones([4, 4])
print(t)

print('shape of t:', t.shape)

t1 = t.view(2, 8)
print('shape of t1:', t1.shape)

t2 = t.view(-1, 8)
print('shape of t2:', t2.shape)

t1[0,0] = 10

print(t[0, 0].item())

print (t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
shape of t: torch.Size([4, 4])
shape of t1: torch.Size([2, 8])
shape of t2: torch.Size([2, 8])
10.0
tensor([[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])


In [3]:
a = torch.empty(5, 4, dtype=torch.float)
print (a)
print(a.dtype)

tensor([[6.0272e+27, 4.5908e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.0712e+27, 4.5908e-41],
        [0.0000e+00, 0.0000e+00, 3.8983e-27, 4.5908e-41],
        [0.0000e+00, 0.0000e+00,        nan, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]])
torch.float32


In [4]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.dtype)

tensor([[-0.9606,  0.2111, -0.5098,  0.3270, -0.9663, -0.1154, -1.4709],
        [ 1.2724,  1.2059,  0.3888, -0.0078,  1.5804, -1.3624, -1.3922],
        [-0.4629,  1.4374, -0.7028,  1.1323,  0.5191, -1.1186, -1.5683],
        [-1.0850, -1.5958,  0.0322, -0.5978,  0.1110,  0.4870, -1.3241],
        [ 0.1471,  0.0996, -1.2445,  1.3746, -1.0573,  0.6674,  0.1917]],
       dtype=torch.float64)
torch.float64


In [5]:
a.fill_(3.5)
b = a.add(4.0)
# a.add_(4.0)
print(a)
print(b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]],
       dtype=torch.float64)
tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)


In [6]:
a = torch.randn(2,3, dtype=torch.float)
print(a)
c = a[0, 2]
print(c)

tensor([[ 0.2438, -1.1430, -0.5280],
        [ 0.1452, -1.2483, -0.0096]])
tensor(-0.5280)


In [7]:
c = a[0:2, 1:3]
print(c)

tensor([[-1.1430, -0.5280],
        [-1.2483, -0.0096]])


In [32]:
z = torch.empty(5, 2)
print(z)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[1.4013e-43, 0.0000e+00],
        [1.4013e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00],
        [1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.]])


In [9]:
x = torch.ones(5, 5)
print(x)

x.index_add_(1, torch.tensor([4, 0], dtype=torch.long), z)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.]])


In [10]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [12]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b) 

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [34]:
print(torch.cuda.is_available())

True


In [14]:
if torch.cuda.is_available():

    a = torch.full((10,), 3, device=torch.device("cuda:0"))
    print(type(a))
    b = a.to(torch.device("cpu"))

c:\program files\python36\lib\site-packages\torch\cuda\__init__.py:117: UserWarning: 
    Found GPU0 GeForce GT 750M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\a\w\1\s\windows\pytorch\aten\src\thc\generic/THCTensorMath.cu:14

## Autograd

In [15]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
print(x)

tensor([1., 2., 3.], requires_grad=True)


In [16]:
w = x * 2
y = w.sum()

print(w)
print(y)

print(w.grad_fn)
print(y.grad_fn)

tensor([2., 4., 6.], grad_fn=<MulBackward0>)
tensor(12., grad_fn=<SumBackward0>)


In [17]:
y.backward()

In [18]:
print(w.grad)  # gradient is computed only w.r.t. graph leaves
print(x.grad)

None
tensor([2., 2., 2.])


In [19]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
w = x * 2
y = w.sum()

y.backward(retain_graph=True)

print(w.grad)  # gradient is computed only w.r.t. graph leaves
print(x.grad)

y.backward()

print(x.grad) # accumulating gradient 

None
tensor([2., 2., 2.])
tensor([4., 4., 4.])


In [20]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
w = x * 2
y = w.sum()

y.backward()
print(x.grad)

w = x * 2
y = w.sum()

y.backward()
print(x.grad)  # accumulating gradient

tensor([2., 2., 2.])
tensor([4., 4., 4.])


### Locally disabling gradient computation

In [22]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)

with torch.no_grad():
    w = x * 2
    y = w.sum()
    
print(y.requires_grad)
print(x.grad)

False
None


### detach

In [23]:
x = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)
print(x)
print(x.numpy())  ##error


tensor([1., 2., 3.], requires_grad=True)


RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [24]:
a = x.detach()
print(a)
print(a.numpy())

a[0] = 2.
print(x)

print(x.requires_grad)
print(a.requires_grad)

tensor([1., 2., 3.])
[1. 2. 3.]
tensor([2., 2., 3.], requires_grad=True)
True
False


In [25]:
b = x.clone().detach()
b[0] = 3.
print(x)
print(b)

tensor([2., 2., 3.], requires_grad=True)
tensor([3., 2., 3.])


In [26]:
# in-place detach
x.detach_().numpy()
print(x)
print(x.requires_grad)

tensor([2., 2., 3.])
False


### Train a shallow net - Numpy vs Pytorch

In [27]:
import numpy as np

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t,"------->", loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 -------> 49296443.61824
1 -------> 54187626.30186035
2 -------> 52586434.939787515
3 -------> 36840957.31626769
4 -------> 18025770.103716694
5 -------> 7294451.621323355
6 -------> 3389683.4928840627
7 -------> 2074772.775212025
8 -------> 1528188.5100554563
9 -------> 1218788.2430667912
10 -------> 1003578.9947752419
11 -------> 839410.6453235886
12 -------> 709449.2272592331
13 -------> 604267.1866932148
14 -------> 518131.0484267704
15 -------> 446982.92873274244
16 -------> 387684.06467675767
17 -------> 337898.4524261534
18 -------> 295837.16935249546
19 -------> 260081.0034696145
20 -------> 229510.89479177853
21 -------> 203312.26406422863
22 -------> 180697.36664177914
23 -------> 161092.9656963374
24 -------> 144042.71415889254
25 -------> 129156.43170987215
26 -------> 116100.11129293067
27 -------> 104605.16452378513
28 -------> 94450.06030034294
29 -------> 85458.56560070353
30 -------> 77466.38624705595
31 -------> 70346.04556575735
32 -------> 63989.33457531284
33 ----

In [29]:
import torch


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
#     if t % 100 == 99:
    print(t, "------->", loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    # Update weights using gradient descent
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 -------> 31917524.0
1 -------> 29315808.0
2 -------> 28159078.0
3 -------> 24961372.0
4 -------> 18918446.0
5 -------> 12358803.0
6 -------> 7222443.0
7 -------> 4123861.0
8 -------> 2453943.25
9 -------> 1590925.625
10 -------> 1126923.75
11 -------> 857272.5625
12 -------> 684531.0
13 -------> 563333.5625
14 -------> 472434.75
15 -------> 401172.46875
16 -------> 343531.8125
17 -------> 296137.5
18 -------> 256636.34375
19 -------> 223400.8125
20 -------> 195276.609375
21 -------> 171306.984375
22 -------> 150774.5
23 -------> 133102.328125
24 -------> 117842.2109375
25 -------> 104624.109375
26 -------> 93139.6328125
27 -------> 83115.71875
28 -------> 74341.8203125
29 -------> 66644.03125
30 -------> 59864.41796875
31 -------> 53880.03125
32 -------> 48579.9453125
33 -------> 43875.71875
34 -------> 39694.40625
35 -------> 35975.34375
36 -------> 32652.630859375
37 -------> 29679.46875
38 -------> 27017.556640625
39 -------> 24626.3828125
40 -------> 22477.0
41 -------> 20541.291